spring.application.name=jwtauthenticationwithdatabase

#PostgreSQL
# spring.datasource.url=jdbc:postgresl://localhost:5432/hello
# spring.datasource.username=sochtech254
# spring.datasource.password=sochtech254
# spring.jpa.database=POSTGRESQL
# spring.jpa.show.sql=true
# spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# h2-Console
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Port
server.port=9090

# JWT
spring.app.jwtSecret=mysecretKey1234509876qwertyuiopasdfghjklzxcvbnm
spring.app.jwtExpirationInMs=300000000000000000

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.sochtech.jwtauthenticationwithdatabase=DEBUG